name: Pull Request Validation

on:
  pull_request:
    branches: [ main, master ]
    types: [opened, synchronize, reopened, ready_for_review]

env:
  PYTHON_VERSION: "3.9"

jobs:
  validate-pr:
    name: Validate Pull Request
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
    - name: Checkout PR code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 1
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black mypy pytest
        
    - name: Check PR title format
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        echo "PR Title: $PR_TITLE"
        
        # Check if title follows conventional commits format
        if [[ ! "$PR_TITLE" =~ ^(feat|fix|docs|style|refactor|test|chore|perf|ci|build)(\(.+\))?: .+ ]]; then
          echo "❌ PR title should follow conventional commits format:"
          echo "   feat: add new feature"
          echo "   fix: fix bug"
          echo "   docs: update documentation"
          echo "   style: format code"
          echo "   refactor: refactor code"
          echo "   test: add tests"
          echo "   chore: maintenance"
          echo "   perf: performance improvement"
          echo "   ci: CI/CD changes"
          echo "   build: build system changes"
          exit 1
        else
          echo "✅ PR title format is correct"
        fi
        
    - name: Check for required files
      run: |
        echo "✅ Checking Python files in PR"
        find . -name "*.py" -type f | grep -E "(src/|plugin)" || echo "No Python files found"
        
        echo "✅ Checking test files"
        find . -name "*test*.py" -type f || echo "No test files found"
        
    - name: Run quick tests
      run: |
        echo "Running quick validation tests..."
        
        # Test plugin syntax
        python -m py_compile plugin_modular.py
        
        # Test all modules compile
        for file in src/*.py; do
          python -m py_compile "$file"
        done
        
        # Run modular tests
        python test_modular.py
        
    - name: Check code formatting
      run: |
        echo "Checking code formatting..."
        black --check --diff src/ *.py || {
          echo "❌ Code formatting issues found"
          echo "Run 'black src/ *.py' to fix formatting"
          exit 1
        }
        
    - name: Run linting
      run: |
        echo "Running linting..."
        flake8 src/ *.py --max-line-length=88 --extend-ignore=E203,W503 || {
          echo "❌ Linting issues found"
          exit 1
        }
        
    - name: Check for security issues
      run: |
        pip install bandit
        echo "Running security check..."
        bandit -r src/ -f json || {
          echo "⚠️  Security issues found, please review"
        }
        
    - name: Analyze changes
      run: |
        echo "Analyzing PR structure..."
        
        # Count Python files
        PYTHON_FILES=$(find . -name "*.py" -type f | wc -l)
        echo "Python files in PR: $PYTHON_FILES"
        
        # Check for large files
        find . -name "*.py" -type f -exec wc -l {} + | sort -n | tail -5
        
        echo "✅ Change analysis completed"
        
    - name: Check documentation
      run: |
        echo "Checking documentation..."
        
        # Check if documentation files exist
        if [ -f "README.md" ]; then
          echo "✅ README.md exists"
        else
          echo "⚠️  README.md missing"
        fi
        
        if [ -f "CHANGELOG.md" ]; then
          echo "✅ CHANGELOG.md exists"
        else
          echo "⚠️  CHANGELOG.md missing"
        fi
        
        # Count documentation files
        DOC_FILES=$(find . -name "*.md" -type f | wc -l)
        echo "Documentation files: $DOC_FILES"

  test-compatibility:
    name: Test Compatibility
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    
    steps:
    - name: Checkout PR code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Test plugin compatibility
      run: |
        echo "Testing with Python ${{ matrix.python-version }}"
        
        # Test compilation
        python -m py_compile plugin_modular.py
        for file in src/*.py; do
          python -m py_compile "$file"
        done
        
        # Test import
        python -c "
        import sys
        sys.path.insert(0, 'src')
        from plugin_modular import create_test_plugin
        plugin = create_test_plugin()
        print('✅ Plugin compatible with Python ${{ matrix.python-version }}')
        "
        
        # Run tests
        python test_modular.py

  performance-check:
    name: Performance Check
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
    - name: Checkout PR code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Performance test
      run: |
        python3 -c "
        import time
        import tracemalloc
        import sys
        sys.path.insert(0, 'src')
        
        print('🔍 Running performance test...')
        
        # Memory test
        tracemalloc.start()
        start_time = time.time()
        
        from plugin_modular import create_test_plugin
        plugin = create_test_plugin()
        
        import_time = time.time() - start_time
        current, peak = tracemalloc.get_traced_memory()
        tracemalloc.stop()
        
        print(f'✅ Import time: {import_time:.3f}s')
        print(f'✅ Peak memory: {peak/1024/1024:.2f}MB')
        
        # Basic performance thresholds
        if import_time > 5.0:
            print('⚠️  Import time seems slow (>5s)')
        if peak > 50*1024*1024:  # 50MB
            print('⚠️  Memory usage seems high (>50MB)')
        
        print('✅ Performance test completed')
        "

  comment-pr:
    name: Comment on PR
    runs-on: ubuntu-latest
    needs: [validate-pr, test-compatibility, performance-check]
    if: always() && github.event.pull_request.draft == false
    
    steps:
    - name: Comment PR results
      uses: actions/github-script@v6
      with:
        script: |
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          
          // Check if we already commented
          const botComment = comments.find(comment => 
            comment.user.type === 'Bot' && 
            comment.body.includes('🤖 PR Validation Results')
          );
          
          const validationStatus = '${{ needs.validate-pr.result }}';
          const compatibilityStatus = '${{ needs.test-compatibility.result }}';
          const performanceStatus = '${{ needs.performance-check.result }}';
          
          let statusEmoji = '✅';
          if (validationStatus === 'failure' || compatibilityStatus === 'failure' || performanceStatus === 'failure') {
            statusEmoji = '❌';
          } else if (validationStatus === 'cancelled' || compatibilityStatus === 'cancelled' || performanceStatus === 'cancelled') {
            statusEmoji = '⚠️';
          }
          
          const commentBody = `
          ## 🤖 PR Validation Results ${statusEmoji}
          
          | Check | Status |
          |-------|--------|
          | Code Validation | ${validationStatus === 'success' ? '✅' : validationStatus === 'failure' ? '❌' : '⚠️'} |
          | Compatibility | ${compatibilityStatus === 'success' ? '✅' : compatibilityStatus === 'failure' ? '❌' : '⚠️'} |
          | Performance | ${performanceStatus === 'success' ? '✅' : performanceStatus === 'failure' ? '❌' : '⚠️'} |
          
          ${validationStatus === 'failure' ? '❌ **Code validation failed** - Please check the logs and fix the issues.' : ''}
          ${compatibilityStatus === 'failure' ? '❌ **Compatibility tests failed** - Please ensure compatibility with all Python versions.' : ''}
          ${performanceStatus === 'failure' ? '❌ **Performance regression detected** - Please optimize the changes.' : ''}
          
          ---
          *This comment was automatically generated by the PR validation workflow.*
          `;
          
          if (botComment) {
            // Update existing comment
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: commentBody
            });
          } else {
            // Create new comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody
            });
          }